env:
  global:
  - $GH_REPO="salem84/salem84.github.io"
  - $GIT_EMAIL="salem84@users.noreply.github.com"
  - $GIT_NAME="salem84"
  - secure: "BtPPX+uCBIXzKyO2qSDOBRP3o14jffmadIomXKKX/cz4jai/Ic1CzH/3GivfYA+zLbY2sQpNukEbh83jsuVYjvfAlXCXa+iffcgrVveV7xliNgLAxDiU1RAD25snOKowo1wXRVD4y/v87hIT0ch/wi6cRPBLJGz+90Ov/rR1nO4="
language: node_js
script:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then node_modules/.bin/docpad deploy-ghpages --env static; fi
branches:
  only:
    - master
before_script:
- chmod ugo+x prebuild.sh
- ./prebuild.sh