env:
  global:
  - $GH_REPO="salem84/docpad-blog"
  - $GIT_EMAIL="salem84@users.noreply.github.com"
  - $GIT_NAME="salem84"
language: node_js
script:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then node_modules/.bin/docpad deploy-ghpages --env static; fi
branches:
  only:
    - master
